// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryAllocation } from "./MemoryAllocation";

export interface JavaPreferences { maximum_memory_allocation: MemoryAllocation, }