// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Progress } from "./Progress";

export interface NamedProgress { title: string, subtitle: string | null, progress: Progress, }