// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OfflineSession } from "./OfflineSession";
import type { PlasmoSession } from "./PlasmoSession";

export type SessionEnum = { type: "none" } | { type: "offline", content: OfflineSession } | { type: "plasmo", content: PlasmoSession };